/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/systems/{system_id}/nodes/{code}/translations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Translations
         * @description All cross-system mappings for a code in one call.
         */
        get: operations["get_translations_api_v1_systems__system_id__nodes__code__translations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}/siblings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Siblings
         * @description Other nodes at the same level under the same parent.
         */
        get: operations["get_siblings_api_v1_systems__system_id__nodes__code__siblings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}/subtree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Subtree
         * @description Aggregate stats for all nodes under a given code.
         */
        get: operations["get_subtree_api_v1_systems__system_id__nodes__code__subtree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Systems
         * @description Side-by-side top-level sectors for two systems.
         */
        get: operations["compare_systems_api_v1_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Diff
         * @description Nodes in system A with no equivalence mapping to system B.
         */
        get: operations["get_system_diff_api_v1_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve Code
         * @description Find all systems that contain a given code.
         */
        get: operations["resolve_code_api_v1_nodes__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Systems Stats
         * @description Per-system leaf and total node counts.
         */
        get: operations["get_systems_stats_api_v1_systems_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Systems
         * @description List all classification systems, optionally filtered by country, category, name query, or grouped.
         */
        get: operations["list_systems_api_v1_systems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Detail
         * @description Get a classification system with its root nodes.
         */
        get: operations["get_system_detail_api_v1_systems__system_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Detail
         * @description Get a single classification node.
         */
        get: operations["get_node_detail_api_v1_systems__system_id__nodes__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Children
         * @description Get direct children of a node.
         */
        get: operations["get_node_children_api_v1_systems__system_id__nodes__code__children_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}/ancestors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Ancestors
         * @description Get the path from root to this node.
         */
        get: operations["get_node_ancestors_api_v1_systems__system_id__nodes__code__ancestors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}/equivalences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Equivalences
         * @description Get cross-system equivalences for a node.
         */
        get: operations["get_node_equivalences_api_v1_systems__system_id__nodes__code__equivalences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Taxonomy For Node
         * @description Generate AI-suggested sub-classifications for a node (preview only, no DB write).
         */
        post: operations["generate_taxonomy_for_node_api_v1_systems__system_id__nodes__code__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/nodes/{code}/generate/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Generated Taxonomy
         * @description Persist user-accepted AI-generated nodes to the database.
         */
        post: operations["accept_generated_taxonomy_api_v1_systems__system_id__nodes__code__generate_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Full-text search across all classification systems.
         */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equivalences/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Crosswalk Stats
         * @description Get counts of equivalence edges per system pair or per edge kind.
         */
        get: operations["crosswalk_stats_api_v1_equivalences_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{source}/crosswalk/{target}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Crosswalk Graph
         * @description Get a graph of crosswalk edges between two systems for visualization.
         */
        get: operations["crosswalk_graph_api_v1_systems__source__crosswalk__target__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{source}/crosswalk/{target}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Crosswalk Sections
         * @description Get a section-level summary of crosswalk edges between two systems.
         *
         *     Returns top-level groupings with edge counts for progressive drill-down.
         */
        get: operations["crosswalk_sections_api_v1_systems__source__crosswalk__target__sections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Countries
         * @description Return countries that have at least one applicable classification system.
         *
         *     Used by the frontend country-filter dropdown. Sorted alphabetically by
         *     country title (from iso_3166_1). Countries whose ISO 3166-1 node has not
         *     been ingested are excluded so the dropdown never shows bare codes.
         */
        get: operations["list_countries_api_v1_countries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Countries Stats
         * @description Return per-country taxonomy coverage stats for all countries.
         *
         *     Used by the world map visualization on the home page.
         *     Returns a list of country objects with:
         *     - country_code: ISO 3166-1 alpha-2
         *     - system_count: number of applicable classification systems
         *     - has_official: whether the country has its own official national standard
         *     - sector_strength_count: number of sector strengths from the geo-sector crosswalk
         */
        get: operations["get_countries_stats_api_v1_countries_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries/{country_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Country Profile
         * @description Return taxonomy profile for a country.
         *
         *     Includes:
         *     - Country metadata (from iso_3166_1 if ingested)
         *     - Applicable classification systems ordered by relevance
         *       (official national system, regional bloc system, UN recommended, historical)
         *     - Known sector strengths (from the geo-sector crosswalk)
         *
         *     country_code: ISO 3166-1 alpha-2 code (e.g. DE, PK, MX, ID, US)
         */
        get: operations["get_country_profile_api_v1_countries__country_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user account.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login with email and password.
         *
         *     Failed attempts are tracked in a sliding window keyed by source IP
         *     and target email; repeated failures return 429 to blunt credential
         *     stuffing. Successful logins clear the counters for that IP+email.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get current user profile.
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Api Keys
         * @description List all API keys for the current user.
         */
        get: operations["list_api_keys_api_v1_auth_keys_get"];
        put?: never;
        /**
         * Create Api Key
         * @description Create a new API key for the current user.
         */
        post: operations["create_api_key_api_v1_auth_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deactivate Api Key
         * @description Deactivate an API key.
         */
        delete: operations["deactivate_api_key_api_v1_auth_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/{provider}/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Authorize
         * @description Return the provider authorization URL.
         *
         *     The frontend should redirect the user to this URL.
         *     The state parameter embeds the redirect_to destination so the callback
         *     can send the user back to the right place.
         */
        get: operations["authorize_api_v1_auth_oauth__provider__authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Callback
         * @description Handle the provider redirect back to our server.
         *
         *     Exchanges the code for an access token, fetches the user profile,
         *     upserts the user in the database, issues a JWT, and redirects to the
         *     frontend with ?token=<jwt>&email=...&name=...
         */
        get: operations["callback_api_v1_auth_oauth__provider__callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Nodes
         * @description Download all nodes in a classification system as CSV.
         *
         *     Requires authentication. Returns rows sorted by seq_order.
         */
        get: operations["export_nodes_api_v1_systems__system_id__export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/systems/{system_id}/crosswalk/{target_id}/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Crosswalk
         * @description Download crosswalk edges between two systems as CSV.
         *
         *     Requires authentication. Returns edges in source -> target direction only.
         */
        get: operations["export_crosswalk_api_v1_systems__system_id__crosswalk__target_id__export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit Provenance
         * @description Aggregate audit report for data trustworthiness review.
         *
         *     Returns provenance tier breakdown, systems missing file hashes,
         *     structural derivation accounting, and skeleton system detection.
         */
        get: operations["audit_provenance_api_v1_audit_provenance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Classify Business
         * @description Classify a business/product/occupation description against taxonomy systems.
         *
         *     Requires Pro or Enterprise tier.
         */
        post: operations["classify_business_api_v1_classify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classify/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Classify Demo
         * @description Public classify endpoint gated by email only.
         *
         *     Returns a limited result set (5 systems, 3 results each). Records
         *     the email as a lead.
         */
        post: operations["classify_demo_api_v1_classify_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Contact
         * @description Submit an enterprise inquiry or general contact form.
         *
         *     Delivers the message via the configured webhook. No admin email
         *     is ever exposed to the client.
         */
        post: operations["submit_contact_api_v1_contact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mcp Http Info
         * @description Friendly probe response so browsers/GET probes don't 405.
         */
        get: operations["mcp_http_info_mcp_get"];
        put?: never;
        /**
         * Mcp Http Bridge
         * @description Handle one MCP JSON-RPC message over HTTP POST.
         */
        post: operations["mcp_http_bridge_mcp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/systems.jsonl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Systems Jsonl
         * @description Export all classification systems as JSONL. Requires Pro+ tier.
         */
        get: operations["export_systems_jsonl_api_v1_export_systems_jsonl_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/systems/{system_id}/nodes.jsonl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Nodes Jsonl
         * @description Export all nodes in a system as JSONL. Requires Pro+ tier.
         */
        get: operations["export_nodes_jsonl_api_v1_export_systems__system_id__nodes_jsonl_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/crosswalks.jsonl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Crosswalks Jsonl
         * @description Export all crosswalk edges as JSONL. Requires Enterprise tier.
         */
        get: operations["export_crosswalks_jsonl_api_v1_export_crosswalks_jsonl_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wiki": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Wiki Pages
         * @description List all wiki guide pages.
         */
        get: operations["list_wiki_pages_api_v1_wiki_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wiki/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wiki Page
         * @description Get a single wiki page by slug.
         */
        get: operations["get_wiki_page_api_v1_wiki__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Return liveness + database reachability in a single round trip.
         *
         *     Response shape:
         *       { "status": "ok" | "degraded", "db": "ok" | "fail", "latency_ms": 0 }
         *
         *     Returns 200 when the pool is reachable and can run SELECT 1,
         *     503 when the database probe fails.
         */
        get: operations["healthz_api_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Return the app version, git SHA, and build time.
         *
         *     Lets operators verify which image is actually running behind a
         *     load balancer. Values are read from env (APP_VERSION, GIT_SHA,
         *     BUILD_TIME) injected at container build time.
         */
        get: operations["version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/robots.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Robots Txt */
        get: operations["robots_txt_robots_txt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llms.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Llms Txt */
        get: operations["llms_txt_llms_txt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llms-full.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Llms Full Txt */
        get: operations["llms_full_txt_llms_full_txt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptTaxonomyRequest */
        AcceptTaxonomyRequest: {
            /** Nodes */
            nodes: components["schemas"]["GeneratedNode"][];
        };
        /** ApiKeyCreatedResponse */
        ApiKeyCreatedResponse: {
            /** Key */
            key: string;
            api_key: components["schemas"]["ApiKeyResponse"];
        };
        /** ApiKeyResponse */
        ApiKeyResponse: {
            /** Id */
            id: string;
            /** Key Prefix */
            key_prefix: string;
            /** Name */
            name: string;
            /** Is Active */
            is_active: boolean;
            /** Last Used At */
            last_used_at: string | null;
            /** Created At */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
        };
        /** AuditProvenanceResponse */
        AuditProvenanceResponse: {
            /** Total Systems */
            total_systems: number;
            /** Total Nodes */
            total_nodes: number;
            /** Provenance Tiers */
            provenance_tiers: components["schemas"]["ProvenanceTierSummary"][];
            /** Official Missing Hash */
            official_missing_hash: components["schemas"]["SystemResponse"][];
            /** Structural Derivation Count */
            structural_derivation_count: number;
            /** Structural Derivation Nodes */
            structural_derivation_nodes: number;
            /** Skeleton Systems */
            skeleton_systems: components["schemas"]["SystemResponse"][];
        };
        /** ClassifyDemoRequest */
        ClassifyDemoRequest: {
            /**
             * Email
             * @description Lead email for follow-up
             */
            email: string;
            /**
             * Text
             * @description Business/product/occupation description
             */
            text: string;
            /**
             * Countries
             * @description Optional ISO 3166-1 alpha-2 country codes. When supplied, classify against the systems applicable to those countries (plus globally recommended standards like ISIC Rev 4) instead of the default demo set.
             */
            countries?: string[] | null;
        };
        /** ClassifyDemoResponse */
        ClassifyDemoResponse: {
            /** Query */
            query: string;
            /**
             * Domain Matches
             * @description Matches from curated WoT Domain taxonomies (system_id starts 'domain_').
             */
            domain_matches?: unknown[];
            /**
             * Standard Matches
             * @description Matches from official standard systems (NAICS, ISIC, NACE, SIC, SOC, ...).
             */
            standard_matches?: unknown[];
            /** Disclaimer */
            disclaimer: string;
            /** Report Issue Url */
            report_issue_url: string;
            /**
             * Demo
             * @default true
             */
            demo: boolean;
            /** Upgrade Cta */
            upgrade_cta: string;
            /**
             * Compound
             * @default false
             */
            compound: boolean;
            /** Atoms */
            atoms?: unknown[] | null;
            /** Hero */
            hero?: {
                [key: string]: unknown;
            } | null;
            /** Cta */
            cta?: {
                [key: string]: unknown;
            } | null;
            /**
             * Llm Used
             * @default false
             */
            llm_used: boolean;
            /**
             * Llm Keywords
             * @default []
             */
            llm_keywords: unknown[];
            /**
             * Scope
             * @description Present only when `countries` was supplied. Mirrors the shape returned by the paid /classify endpoint.
             */
            scope?: {
                [key: string]: unknown;
            } | null;
        };
        /** ClassifyRequest */
        ClassifyRequest: {
            /**
             * Text
             * @description Free-text to classify
             */
            text: string;
            /**
             * Systems
             * @description Optional list of system IDs to search. Default: major systems.
             */
            systems?: string[] | null;
            /**
             * Countries
             * @description Optional ISO 3166-1 alpha-2 country codes. Scopes candidates to systems applicable to these countries plus universal recommended standards (UN/WCO/WHO). Overrides `systems` when set.
             */
            countries?: string[] | null;
            /**
             * Limit
             * @description Max matches per system
             * @default 5
             */
            limit: number;
        };
        /** ClassifyResponse */
        ClassifyResponse: {
            /** Query */
            query: string;
            /**
             * Domain Matches
             * @description Matches from curated WoT Domain taxonomies (plain-language, concrete).
             */
            domain_matches?: components["schemas"]["ClassifySystemMatch"][];
            /**
             * Standard Matches
             * @description Matches from official standard systems (NAICS, ISIC, NACE, SIC, SOC, ...).
             */
            standard_matches?: components["schemas"]["ClassifySystemMatch"][];
            /** Crosswalks */
            crosswalks: components["schemas"]["CrosswalkEdge"][];
            /** Disclaimer */
            disclaimer: string;
            /** Report Issue Url */
            report_issue_url: string;
            /** @description Present only when `countries` was supplied. Shows the resolved country-specific vs global candidate systems the classifier used. */
            scope?: components["schemas"]["ScopeInfo"] | null;
        };
        /** ClassifyResult */
        ClassifyResult: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Score */
            score: number;
            /** Level */
            level: number;
            /**
             * Crosswalk Count
             * @description Number of equivalence edges originating from this code. The UI uses this to hide the 'Show crosswalks' affordance for codes with no outgoing edges.
             * @default 0
             */
            crosswalk_count: number;
        };
        /** ClassifySystemMatch */
        ClassifySystemMatch: {
            /** System Id */
            system_id: string;
            /** System Name */
            system_name: string;
            /**
             * Category
             * @description 'domain' for curated WoT taxonomies (system_id starts 'domain_'), 'standard' otherwise.
             */
            category: string;
            /** Results */
            results: components["schemas"]["ClassifyResult"][];
        };
        /** CompareSectorsResponse */
        CompareSectorsResponse: {
            /** System A */
            system_a: components["schemas"]["NodeResponse"][];
            /** System B */
            system_b: components["schemas"]["NodeResponse"][];
        };
        /** ContactRequest */
        ContactRequest: {
            /**
             * Name
             * @description Contact name
             */
            name: string;
            /**
             * Company
             * @description Company name
             */
            company?: string | null;
            /**
             * Email
             * @description Contact email
             */
            email: string;
            /**
             * Message
             * @description Message
             */
            message: string;
        };
        /** ContactResponse */
        ContactResponse: {
            /**
             * Status
             * @default received
             */
            status: string;
            /**
             * Message
             * @default Thank you for your inquiry. We will be in touch shortly.
             */
            message: string;
        };
        /** CreateApiKeyRequest */
        CreateApiKeyRequest: {
            /**
             * Name
             * @default Default
             */
            name: string;
        };
        /** CrosswalkEdge */
        CrosswalkEdge: {
            /** From */
            from: string;
            /** To */
            to: string;
            /** Match Type */
            match_type: string;
            /**
             * Edge Kind
             * @description Computed: '{source}_{target}' where each side is 'domain' if the system_id starts with 'domain_', else 'standard'.
             */
            edge_kind: string;
        };
        /** CrosswalkGraphEdge */
        CrosswalkGraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Match Type */
            match_type: string;
        };
        /** CrosswalkGraphNode */
        CrosswalkGraphNode: {
            /** Id */
            id: string;
            /** System */
            system: string;
            /** Code */
            code: string;
            /** Title */
            title: string;
        };
        /** CrosswalkGraphResponse */
        CrosswalkGraphResponse: {
            /** Source System */
            source_system: string;
            /** Target System */
            target_system: string;
            /** Nodes */
            nodes: components["schemas"]["CrosswalkGraphNode"][];
            /** Edges */
            edges: components["schemas"]["CrosswalkGraphEdge"][];
            /** Total Edges */
            total_edges: number;
            /** Truncated */
            truncated: boolean;
        };
        /** CrosswalkSection */
        CrosswalkSection: {
            /** Source Section */
            source_section: string;
            /** Source Title */
            source_title: string;
            /** Target Section */
            target_section: string;
            /** Target Title */
            target_title: string;
            /** Edge Count */
            edge_count: number;
            /** Exact Count */
            exact_count: number;
        };
        /** CrosswalkSectionsResponse */
        CrosswalkSectionsResponse: {
            /** Source System */
            source_system: string;
            /** Target System */
            target_system: string;
            /** Sections */
            sections: components["schemas"]["CrosswalkSection"][];
            /** Total Edges */
            total_edges: number;
        };
        /** CrosswalkStatResponse */
        CrosswalkStatResponse: {
            /** Source System */
            source_system: string;
            /** Target System */
            target_system: string;
            /** Edge Count */
            edge_count: number;
            /** Exact Count */
            exact_count: number;
            /** Partial Count */
            partial_count: number;
        };
        /** EdgeKindStatResponse */
        EdgeKindStatResponse: {
            /** Edge Kind */
            edge_kind: string;
            /** Edge Count */
            edge_count: number;
            /**
             * Exact Count
             * @default 0
             */
            exact_count: number;
            /**
             * Partial Count
             * @default 0
             */
            partial_count: number;
            /**
             * Broad Count
             * @default 0
             */
            broad_count: number;
        };
        /** EquivalenceResponse */
        EquivalenceResponse: {
            /** Source System */
            source_system: string;
            /** Source Code */
            source_code: string;
            /** Target System */
            target_system: string;
            /** Target Code */
            target_code: string;
            /** Match Type */
            match_type: string;
            /** Notes */
            notes?: string | null;
            /** Source Title */
            source_title?: string | null;
            /** Target Title */
            target_title?: string | null;
            /**
             * Source Category
             * @description Category of source_system: 'domain' or 'standard'.
             * @default standard
             */
            source_category: string;
            /**
             * Target Category
             * @description Category of target_system: 'domain' or 'standard'.
             * @default standard
             */
            target_category: string;
            /**
             * Edge Kind
             * @description One of: standard_standard, standard_domain, domain_standard, domain_domain.
             * @default standard_standard
             */
            edge_kind: string;
        };
        /** GenerateTaxonomyRequest */
        GenerateTaxonomyRequest: {
            /**
             * Count
             * @default 5
             */
            count: number;
        };
        /** GenerateTaxonomyResponse */
        GenerateTaxonomyResponse: {
            /** Parent System Id */
            parent_system_id: string;
            /** Parent Code */
            parent_code: string;
            /** Nodes */
            nodes: components["schemas"]["GeneratedNode"][];
        };
        /** GeneratedNode */
        GeneratedNode: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** NodeResponse */
        NodeResponse: {
            /** Id */
            id: number;
            /** System Id */
            system_id: string;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Level
             * @default 0
             */
            level: number;
            /** Parent Code */
            parent_code?: string | null;
            /** Sector Code */
            sector_code?: string | null;
            /**
             * Is Leaf
             * @default false
             */
            is_leaf: boolean;
            /**
             * Seq Order
             * @default 0
             */
            seq_order: number;
            /**
             * Category
             * @description 'domain' if system_id starts 'domain_', else 'standard'.
             * @default standard
             */
            category: string;
            /** Data Provenance */
            data_provenance?: string | null;
            /** License */
            license?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Source Date */
            source_date?: string | null;
            /** Source File Hash */
            source_file_hash?: string | null;
            /** Source Url For Code */
            source_url_for_code?: string | null;
        };
        /** ProvenanceTierSummary */
        ProvenanceTierSummary: {
            /** Data Provenance */
            data_provenance: string | null;
            /** System Count */
            system_count: number;
            /** Node Count */
            node_count: number;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name?: string | null;
        };
        /** ScopeInfo */
        ScopeInfo: {
            /** Countries */
            countries: string[];
            /** Country Specific Systems */
            country_specific_systems: string[];
            /** Global Standard Systems */
            global_standard_systems: string[];
            /** Candidate Systems */
            candidate_systems: string[];
        };
        /** SubtreeSummaryResponse */
        SubtreeSummaryResponse: {
            /** System Id */
            system_id: string;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Total Nodes */
            total_nodes: number;
            /** Leaf Count */
            leaf_count: number;
            /** Max Depth */
            max_depth: number;
        };
        /** SystemDetailResponse */
        SystemDetailResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Full Name */
            full_name?: string | null;
            /** Region */
            region?: string | null;
            /** Version */
            version?: string | null;
            /** Authority */
            authority?: string | null;
            /** Url */
            url?: string | null;
            /** Tint Color */
            tint_color?: string | null;
            /**
             * Node Count
             * @default 0
             */
            node_count: number;
            /** Source Url */
            source_url?: string | null;
            /** Source Date */
            source_date?: string | null;
            /** Data Provenance */
            data_provenance?: string | null;
            /** License */
            license?: string | null;
            /** Source File Hash */
            source_file_hash?: string | null;
            /**
             * Category
             * @description 'domain' for curated WoT Domain taxonomies (id starts 'domain_'), 'standard' otherwise.
             * @default standard
             */
            category: string;
            /**
             * Roots
             * @default []
             */
            roots: components["schemas"]["NodeResponse"][];
        };
        /** SystemGranularityResponse */
        SystemGranularityResponse: {
            /** System Id */
            system_id: string;
            /** Total Nodes */
            total_nodes: number;
            /** Leaf Nodes */
            leaf_nodes: number;
        };
        /** SystemResponse */
        SystemResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Full Name */
            full_name?: string | null;
            /** Region */
            region?: string | null;
            /** Version */
            version?: string | null;
            /** Authority */
            authority?: string | null;
            /** Url */
            url?: string | null;
            /** Tint Color */
            tint_color?: string | null;
            /**
             * Node Count
             * @default 0
             */
            node_count: number;
            /** Source Url */
            source_url?: string | null;
            /** Source Date */
            source_date?: string | null;
            /** Data Provenance */
            data_provenance?: string | null;
            /** License */
            license?: string | null;
            /** Source File Hash */
            source_file_hash?: string | null;
            /**
             * Category
             * @description 'domain' for curated WoT Domain taxonomies (id starts 'domain_'), 'standard' otherwise.
             * @default standard
             */
            category: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            /** Tier */
            tier: string;
            /** Created At */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WikiPageDetail */
        WikiPageDetail: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Content Markdown */
            content_markdown: string;
        };
        /** WikiPageSummary */
        WikiPageSummary: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_translations_api_v1_systems__system_id__nodes__code__translations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquivalenceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_siblings_api_v1_systems__system_id__nodes__code__siblings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subtree_api_v1_systems__system_id__nodes__code__subtree_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubtreeSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_systems_api_v1_compare_get: {
        parameters: {
            query: {
                /** @description First system ID */
                a: string;
                /** @description Second system ID */
                b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareSectorsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_diff_api_v1_diff_get: {
        parameters: {
            query: {
                /** @description Source system ID */
                a: string;
                /** @description Target system to check coverage against */
                b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_code_api_v1_nodes__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_systems_stats_api_v1_systems_stats_get: {
        parameters: {
            query?: {
                system_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemGranularityResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_systems_api_v1_systems_get: {
        parameters: {
            query?: {
                /** @description Group results (e.g. 'region') */
                group_by?: string | null;
                /** @description Filter by ISO 3166-1 alpha-2 country code (e.g. DE, PK, MX) */
                country?: string | null;
                /** @description Filter by category: 'domain' for curated Domain taxonomies, 'standard' for official standards (NAICS, ISIC, ...), omit for all. */
                category?: string | null;
                /** @description Optional case-insensitive substring filter across id, name, full_name, authority, and region. */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_detail_api_v1_systems__system_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_detail_api_v1_systems__system_id__nodes__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_children_api_v1_systems__system_id__nodes__code__children_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_ancestors_api_v1_systems__system_id__nodes__code__ancestors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_equivalences_api_v1_systems__system_id__nodes__code__equivalences_get: {
        parameters: {
            query?: {
                /** @description Filter by edge kind (comma-separated). One or more of: standard_standard, standard_domain, domain_standard, domain_domain. */
                edge_kind?: string | null;
            };
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquivalenceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_taxonomy_for_node_api_v1_systems__system_id__nodes__code__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateTaxonomyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateTaxonomyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_generated_taxonomy_api_v1_systems__system_id__nodes__code__generate_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptTaxonomyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                /** @description Filter by system ID. Pass multiple times to match any of several systems: ?system_id=naics_2022&system_id=isic_rev4. */
                system_id?: string[] | null;
                /** @description Filter by system ID (alias, repeatable). */
                system?: string[] | null;
                /** @description Filter by category: 'domain' or 'standard'. Omit for both. */
                category?: string | null;
                /** @description Optional ISO 3166-1 alpha-2 country codes. Scopes results to systems applicable to these countries plus universal recommended standards (UN/WCO/WHO). Pass multiple times to union: ?countries=US&countries=CA. */
                countries?: string[] | null;
                /** @description Max results */
                limit?: number;
                /** @description Return results grouped by system */
                grouped?: boolean;
                /** @description Include ancestors and children for each match */
                context?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crosswalk_stats_api_v1_equivalences_stats_get: {
        parameters: {
            query?: {
                /** @description Filter to a specific system */
                system_id?: string | null;
                /** @description Grouping dimension. Omit (default) for system-pair stats. Pass 'edge_kind' for counts grouped by the four edge kinds (standard_standard, standard_domain, domain_standard, domain_domain). */
                group_by?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrosswalkStatResponse"][] | components["schemas"]["EdgeKindStatResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crosswalk_graph_api_v1_systems__source__crosswalk__target__graph_get: {
        parameters: {
            query?: {
                /** @description Max edges to return */
                limit?: number;
                /** @description Filter to edges within this section code */
                section?: string | null;
            };
            header?: never;
            path: {
                source: string;
                target: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrosswalkGraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crosswalk_sections_api_v1_systems__source__crosswalk__target__sections_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: string;
                target: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrosswalkSectionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_countries_api_v1_countries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_countries_stats_api_v1_countries_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_country_profile_api_v1_countries__country_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_api_keys_api_v1_auth_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyResponse"][];
                };
            };
        };
    };
    create_api_key_api_v1_auth_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApiKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_api_key_api_v1_auth_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorize_api_v1_auth_oauth__provider__authorize_get: {
        parameters: {
            query?: {
                redirect_to?: string | null;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_api_v1_auth_oauth__provider__callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_nodes_api_v1_systems__system_id__export_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_crosswalk_api_v1_systems__system_id__crosswalk__target_id__export_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
                target_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_provenance_api_v1_audit_provenance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditProvenanceResponse"];
                };
            };
        };
    };
    classify_business_api_v1_classify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classify_demo_api_v1_classify_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassifyDemoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyDemoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_contact_api_v1_contact_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mcp_http_info_mcp_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    mcp_http_bridge_mcp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    export_systems_jsonl_api_v1_export_systems_jsonl_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    export_nodes_jsonl_api_v1_export_systems__system_id__nodes_jsonl_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                system_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_crosswalks_jsonl_api_v1_export_crosswalks_jsonl_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_wiki_pages_api_v1_wiki_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPageSummary"][];
                };
            };
        };
    };
    get_wiki_page_api_v1_wiki__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WikiPageDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_api_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    robots_txt_robots_txt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    llms_txt_llms_txt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    llms_full_txt_llms_full_txt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
