export type SystemCategory =
  | 'Industry & Trade'
  | 'Occupations & Skills'
  | 'Health & Life Sciences'
  | 'Education'
  | 'Finance'
  | 'Sustainability & ESG'
  | 'Science & Research'
  | 'Geography'
  | 'Regulations & Compliance'
  | 'Standards & Frameworks'
  | 'Domain Taxonomies'
  | 'Other'

export const CATEGORY_ORDER: readonly SystemCategory[] = [
  'Industry & Trade',
  'Occupations & Skills',
  'Health & Life Sciences',
  'Education',
  'Finance',
  'Sustainability & ESG',
  'Science & Research',
  'Geography',
  'Regulations & Compliance',
  'Standards & Frameworks',
  'Domain Taxonomies',
  'Other',
] as const

const INDUSTRY_PREFIXES = [
  'naics',
  'isic',
  'sic_',
  'nace',
  'anzsic',
  'nic_',
  'jsic',
  'gb_t',
  'ksic',
  'ssic',
  'msic',
  'tsic',
  'psic',
  'kbli',
  'vsic',
  'bsic',
  'slsic',
  'ateco',
  'naf_',
  'pkd',
  'sbi',
  'sni',
  'db07',
  'tol_',
  'cae_',
  'cnae',
  'nkd',
  'teaor',
  'caen',
  'sk_nace',
  'nkid',
  'emtak',
  'evrk',
  'nk_nace',
  'skd',
  'sn_2007',
  'isat',
  'kd_',
  'nve',
  'caem',
  'kved',
  'ciiu',
  'caeb',
  'clanae',
  'nace_bel',
  'nace_lu',
  'stakod',
  'wz_',
  'onace',
  'noga',
]

const TRADE_PREFIXES = [
  'hs_',
  'hts',
  'schedule_b',
  'cpc_',
  'sitc',
  'bec_',
  'unspsc',
  'prodcom',
  'cpv_',
  'cn_2024',
  'taric',
  'uk_tariff',
  'ncm',
  'ahtn',
  'afcfta',
  'gcc_cct',
  'ecowas',
  'eccn',
  'coicop',
  'nmfc',
  'stcc',
]

const OCCUPATION_PREFIXES = [
  'soc_',
  'isco',
  'onet',
  'o_net',
  'noc_',
  'uk_soc',
  'kldb',
  'rome',
  'anzsco',
  'esco',
  'linkedin_skills',
  'sfia',
  'worldskills',
  'shrm',
  'scor',
  'job_family',
]

const HEALTH_PREFIXES = [
  'icd',
  'loinc',
  'snomed',
  'rxnorm',
  'ndc',
  'dsm',
  'icf',
  'icpc',
  'ichi',
  'gbd',
  'gmdn',
  'hedis',
  'cms_star',
  'atc_who',
  'mesh',
  'nci',
  'ctcae',
  'hcpcs',
  'ms_drg',
  'nucc',
  'cpt',
  'dea',
  'fda',
  'usp_',
  'hl7',
  'dicom',
  'nanda',
  'nic_nursing',
  'icn_nursing',
  'who_essential',
  'cdc_vaccine',
  'who_fctc',
  'icdo3',
  'g_drg',
  'joint_commission',
  'cap_acc',
  'clia',
  'omim',
  'orphanet',
  'edqm',
  'hl7',
  'ash',
]

const EDUCATION_PREFIXES = [
  'cip_',
  'isced',
  'iscedf',
  'digcomp',
  'e_cf',
  'eqf',
  'aqf',
  'ngss',
  'ccss',
  'blooms',
  'uk_nqf',
  'aacsb',
  'abet',
]

const FINANCE_PREFIXES = [
  'gics',
  'icb',
  'basel',
  'wb_income',
  'cfi_iso',
  'bloomberg',
  'refinitiv',
  'swift',
  'iso_20022',
  'payment_card',
  'xbrl',
  'token_std',
  'defi',
  'solvency',
  'mifid',
  'psd2',
  'ifrs',
  'us_gaap',
  'fasb',
  'pcaob',
  'aicpa',
  'adb_sector',
]

const ESG_PREFIXES = [
  'sasb',
  'gri',
  'tnfd',
  'sfdr',
  'eu_taxonomy',
  'tcfd',
  'issb',
  'sbti',
  'sdg',
  'oecd_dac',
  'ghg_',
  'cbam',
  'csrd',
  'emas',
  'un_gp',
  'oecd_mne',
  'ilo_',
  'equator',
  'ifc_perf',
  'ramsar',
  'cbd_',
  'unep',
  'montreal',
  'paris_agree',
  'kimberley',
  'seea',
  'iucn',
  'cites',
  'iea_',
  'irena',
  'faostat',
  'aquastat',
]

const SCIENCE_PREFIXES = [
  'patent_cpc',
  'arxiv',
  'acm_ccs',
  'jel',
  'msc',
  'pacs',
  'lcc',
  'scopus',
  'web_of_science',
  'ford_frascati',
  'anzsrc',
  'era_',
  'udc',
  'dewey',
  'lcsh',
  'unesco_thes',
  'getty',
]

const GEO_PREFIXES = [
  'iso_3166',
  'un_m49',
  'nuts',
  'us_fips',
  'eu_nuts',
]

const REGULATION_PREFIXES = [
  'hipaa',
  'sox',
  'glba',
  'ferpa',
  'coppa',
  'fcra',
  'ada_',
  'osha',
  'nerc',
  'fisma',
  'fedramp',
  'ccpa',
  'cpra',
  'cfpb',
  'sec_',
  'finra',
  'far_',
  'dfars',
  'itar',
  'ear_',
  'clean_air',
  'clean_water',
  'cercla',
  'rcra',
  'tsca',
  'cfr_title',
  'usc_title',
  'fmcsa',
  'dora',
  'nis2',
  'eu_ai_act',
  'eprivacy',
  'reach',
  'rohs',
  'mdr_',
  'ivdr',
  'eu_whistle',
  'weee',
  'eu_pkg',
  'eu_batteries',
  'eu_deforest',
  'dsa_',
  'dma_',
  'cra_',
  'data_act',
  'eu_machinery',
  'irs_form',
  'vat_rate',
  'gdpr',
  'pci_dss',
  'ftc_',
  'fta_',
  'naic_models',
  'ffiec',
  'ada',
  'federal_tax',
  'ccpa_cpra',
]

const STANDARDS_PREFIXES = [
  'iso_',
  'iec_',
  'ieee',
  'w3c',
  'ietf',
  'usb_if',
  'bluetooth',
  'ansi_',
  'asme',
  'astm',
  'ashrae',
  'nist_csf',
  'nist_sp',
  'cis_controls',
  'mitre_',
  'cve',
  'cwe',
  'owasp',
  'cmmi',
  'hitrust',
  'pmbok',
  'prince2',
  'itil',
  'togaf',
  'archimate',
  'cobit',
  'skos',
  'mime',
  'http_status',
  'spdx',
  'isa_audit',
  'nato_',
  'stanag',
  'wco_safe',
  'unclos',
  'fatf',
  'codex_',
  '3gpp',
  'itu_',
  'jedec',
  'semi_',
  'vesa',
  'pci_sig',
  'rics',
  'breeam',
  'leed',
  'cofog',
  'nfpa',
  'ibc_',
  'cmmc',
  'soc_2_',
  'hcpcs_l3',
  'iso_31000',
]

function matchesPrefix(id: string, prefixes: string[]): boolean {
  return prefixes.some((p) => id.startsWith(p))
}

export function classifySystem(id: string): SystemCategory {
  const lid = id.toLowerCase()
  if (lid.startsWith('domain_')) return 'Domain Taxonomies'
  if (matchesPrefix(lid, GEO_PREFIXES)) return 'Geography'
  if (matchesPrefix(lid, HEALTH_PREFIXES)) return 'Health & Life Sciences'
  if (matchesPrefix(lid, EDUCATION_PREFIXES)) return 'Education'
  if (matchesPrefix(lid, OCCUPATION_PREFIXES)) return 'Occupations & Skills'
  if (matchesPrefix(lid, ESG_PREFIXES)) return 'Sustainability & ESG'
  if (matchesPrefix(lid, FINANCE_PREFIXES)) return 'Finance'
  if (matchesPrefix(lid, SCIENCE_PREFIXES)) return 'Science & Research'
  if (matchesPrefix(lid, TRADE_PREFIXES)) return 'Industry & Trade'
  if (matchesPrefix(lid, INDUSTRY_PREFIXES)) return 'Industry & Trade'
  if (matchesPrefix(lid, REGULATION_PREFIXES)) return 'Regulations & Compliance'
  if (matchesPrefix(lid, STANDARDS_PREFIXES)) return 'Standards & Frameworks'
  return 'Other'
}
